// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextMassConsole.Model;

namespace NextMassConsole.Migrations
{
    [DbContext(typeof(NextMassContext))]
    [Migration("20190726131326_Change prop Location to name Coordinates in Church")]
    partial class ChangepropLocationtonameCoordinatesinChurch
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NextMassConsole.Model.Church", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Churches");
                });

            modelBuilder.Entity("NextMassConsole.Model.ChurchUser", b =>
                {
                    b.Property<int>("ChurchId");

                    b.Property<int>("UserId");

                    b.HasKey("ChurchId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChurchUser");
                });

            modelBuilder.Entity("NextMassConsole.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NextMassConsole.Model.Church", b =>
                {
                    b.OwnsMany("NextMassConsole.Model.MassTime", "MassTimes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("ChurchId");

                            b1.Property<int>("Day");

                            b1.Property<int>("Hour");

                            b1.Property<int>("Minute");

                            b1.HasKey("Id");

                            b1.HasIndex("ChurchId");

                            b1.ToTable("MassTime");

                            b1.HasOne("NextMassConsole.Model.Church", "Church")
                                .WithMany("MassTimes")
                                .HasForeignKey("ChurchId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("NextMassConsole.Model.Location", "Coordinates", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Id");

                            b1.ToTable("Churches");

                            b1.HasOne("NextMassConsole.Model.Church")
                                .WithOne("Coordinates")
                                .HasForeignKey("NextMassConsole.Model.Location", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("NextMassConsole.Model.ChurchUser", b =>
                {
                    b.HasOne("NextMassConsole.Model.Church", "Church")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NextMassConsole.Model.User", "User")
                        .WithMany("FavoriteChurches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NextMassConsole.Model.User", b =>
                {
                    b.OwnsOne("NextMassConsole.Model.Location", "DefaultLocation", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Id");

                            b1.ToTable("Users");

                            b1.HasOne("NextMassConsole.Model.User")
                                .WithOne("DefaultLocation")
                                .HasForeignKey("NextMassConsole.Model.Location", "Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
